import type { CharacterSheetState } from "../types/sheet.ts";

export const SHEET_TABS = [
  { id: "overview", label: "Overview" },
  { id: "potentials", label: "Potentials" },
  { id: "actions", label: "Actions" },
  { id: "abilities", label: "Abilities" },
  { id: "inventory", label: "Inventory" },
  { id: "background", label: "Background" },
  { id: "notes", label: "Notes" },
] as const;

export type SheetTabId = (typeof SHEET_TABS)[number]["id"];

export const DEMO_SHEET: CharacterSheetState = {
  header: {
    name: "Gwenhyfridd Cescire",
    archetype: "Dreamer Barbarian / Wizard",
    origin: "Astral exile from Sauztein Geb",
    playerName: "Tobi",
    level: 9,
    tier: "III",
    partyName: "The Crooked Lark",
  },
  marks: {
    total: 7,
    taken: 2,
  },
  experience: {
    beats: 14,
    strings: 6,
    milestones: 1,
  },
  tokens: [
    {
      id: "flavor",
      label: "Flavor",
      current: 3,
      max: 8,
      tone: "gold",
      description: "Personal roleplay currency.",
    },
    {
      id: "spirit",
      label: "Spirit",
      current: 4,
      max: 7,
      tone: "purple",
      communal: true,
      description: "Shared Loom pool for party boons.",
    },
  ],
  armor: [
    {
      id: "coat",
      location: "Body",
      name: "Mossweave Coat",
      kind: "light",
      protectionMax: 2,
      protectionOpen: 1,
      refresh: "move",
    },
    {
      id: "vambrace",
      location: "Arms",
      name: "Astral Vambrace",
      kind: "heavy",
      protectionMax: 1,
      protectionOpen: 1,
      refresh: "manual",
      notes: "Reduces incoming physical damage by a Might volatility roll while open.",
    },
    {
      id: "buckler",
      location: "Offhand",
      name: "Moon Buckler",
      kind: "shield",
      protectionMax: 2,
      protectionOpen: 2,
      refresh: "resistance",
      refreshPotential: "might",
    },
  ],
  potentials: [
    {
      key: "might",
      title: "Might",
      score: 4,
      stress: 1,
      resistance: 0,
      volatilityDieMax: 4,
      skills: [
        { name: "Force", summary: "Striking, lifting, overpowering" },
        { name: "Brace", summary: "Weathering impact", proficient: true },
        { name: "Feat", summary: "Breaking normal limits" },
      ],
      perks: {
        2: { label: "RF", color: "#5fc6ff" },
        3: { label: "DR", color: "#d24c4c" },
      },
    },
    {
      key: "finesse",
      title: "Finesse",
      score: 6,
      stress: 0,
      resistance: 1,
      volatilityDieMax: 6,
      skills: [
        { name: "Sleight", summary: "Manual dexterity", proficient: true },
        { name: "Grace", summary: "Balance and quickness" },
        { name: "Squirm", summary: "Escaping binds" },
      ],
      perks: {
        2: { label: "RF", color: "#5fc6ff" },
        3: { label: "CL", color: "#5fd27c" },
        4: { label: "DR", color: "#d24c4c" },
        5: { label: "BR", color: "#f1a74a" },
      },
    },
    {
      key: "nerve",
      title: "Nerve",
      score: 5,
      stress: 5,
      resistance: 0,
      volatilityDieMax: 6,
      charged: true,
      skills: [
        { name: "Bear", summary: "Endure hurt" },
        { name: "Steel", summary: "Ignore wear" },
        { name: "Grit", summary: "Stay standing", proficient: true },
      ],
      perks: {
        2: { label: "RF", color: "#5fc6ff" },
        3: { label: "CL", color: "#5fd27c" },
        4: { label: "DR", color: "#d24c4c" },
        5: { label: "BR", color: "#f1a74a" },
      },
    },
    {
      key: "seep",
      title: "Seep",
      score: 3,
      stress: 0,
      resistance: 0,
      volatilityDieMax: 4,
      skills: [
        { name: "Frame", summary: "Hold form" },
        { name: "Draw", summary: "Let in change" },
        { name: "Form", summary: "Shape altered matter" },
      ],
      perks: {
        2: { label: "RF", color: "#5fc6ff" },
        3: { label: "DR", color: "#d24c4c" },
      },
    },
    {
      key: "instinct",
      title: "Instinct",
      score: 7,
      stress: 2,
      resistance: 1,
      volatilityDieMax: 6,
      skills: [
        { name: "Reflex", summary: "Snap reactions", proficient: true },
        { name: "Read", summary: "Read the room" },
        { name: "Sense", summary: "Trust the senses" },
      ],
      perks: {
        2: { label: "RF", color: "#5fc6ff" },
        3: { label: "CL", color: "#5fd27c" },
        4: { label: "DR", color: "#d24c4c" },
        5: { label: "BR", color: "#f1a74a" },
      },
    },
    {
      key: "wit",
      title: "Wit",
      score: 5,
      stress: 2,
      resistance: 0,
      volatilityDieMax: 8,
      charged: true,
      skills: [
        { name: "Reason", summary: "Patterns and logic" },
        { name: "Recall", summary: "Facts and memory", proficient: true },
        { name: "Esoterica", summary: "Hidden learning" },
      ],
      perks: {
        2: { label: "RF", color: "#5fc6ff" },
        3: { label: "CL", color: "#5fd27c" },
        4: { label: "DR", color: "#d24c4c" },
        5: { label: "BR", color: "#f1a74a" },
        6: { label: "FR", color: "#a86bff" },
        7: { label: "IM", color: "#4ab0a1" },
      },
    },
    {
      key: "heart",
      title: "Heart",
      score: 6,
      stress: 0,
      resistance: 2,
      volatilityDieMax: 6,
      skills: [
        { name: "Aura", summary: "Presence and body language" },
        { name: "Sway", summary: "Persuasion", proficient: true },
        { name: "Hope", summary: "Inspiration" },
      ],
      perks: {
        2: { label: "RF", color: "#5fc6ff" },
        3: { label: "CL", color: "#5fd27c" },
        4: { label: "DR", color: "#d24c4c" },
        5: { label: "BR", color: "#f1a74a" },
      },
    },
    {
      key: "tether",
      title: "Tether",
      score: 4,
      stress: 2,
      resistance: 0,
      volatilityDieMax: 4,
      skills: [
        { name: "Anchor", summary: "Stay grounded", proficient: true },
        { name: "Grasp", summary: "Understand the strange" },
        { name: "Weave", summary: "Guide ritual and flow" },
      ],
      perks: {
        2: { label: "RF", color: "#5fc6ff" },
        3: { label: "DR", color: "#d24c4c" },
      },
    },
  ],
};
